services:
  postgres:
    container_name: ${PSQL_DB_HOST}
    image: postgres:latest
    environment:
      POSTGRES_DB: ${PSQL_DATABASE}
      POSTGRES_USER: ${PSQL_USER}
      POSTGRES_PASSWORD: ${PSQL_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  pgadmin:
    container_name: ${PGADMIN_HOST}
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "5050:80"
volumes:
  postgres_data: